version: "3"

services:
  master:
    image: gettyimages/spark:2.0.2-hadoop-2.7
    command: spark-class org.apache.spark.deploy.master.Master
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

  worker:
    image: gettyimages/spark:2.0.2-hadoop-2.7
    command: spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    depends_on:
      - master
    ports:
      - 8081:8081
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

  processor:
    image: nexrad-processor
    depends_on:
      - s3_initializer
      - master
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      FULL_RESULTS: ${FULL_RESULTS}
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]

networks:
  default:
